# Kubernetes Namespace for Events Platform
apiVersion: v1
kind: Namespace
metadata:
  name: events-platform
  labels:
    name: events-platform
    app.kubernetes.io/name: events-platform
    app.kubernetes.io/instance: production
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: namespace
    app.kubernetes.io/part-of: events-platform
    app.kubernetes.io/managed-by: kubectl
  annotations:
    description: "Events Platform hybrid Go/Python microservices"
    contact: "dev-team@events-platform.com"
    
---
# Resource Quota for the namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: events-platform-quota
  namespace: events-platform
spec:
  hard:
    requests.cpu: "10"
    requests.memory: "20Gi"
    limits.cpu: "20"
    limits.memory: "40Gi"
    persistentvolumeclaims: "20"
    services: "20"
    secrets: "20"
    configmaps: "20"
    pods: "50"

---
# Network Policy for namespace isolation
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: events-platform-netpol
  namespace: events-platform
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow traffic from same namespace
  - from:
    - namespaceSelector:
        matchLabels:
          name: events-platform
  # Allow traffic from monitoring namespace
  - from:
    - namespaceSelector:
        matchLabels:
          name: monitoring
  # Allow traffic from ingress controllers
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
  egress:
  # Allow all egress traffic (customize as needed)
  - {}